import type {Metadata} from "next";
import {Amaranth, Geist_Mono, Lilita_One, Noto_Sans_Mono, Roboto_Mono} from "next/font/google";
import "./globals.css";

const lilita = Lilita_One({
    subsets: ["latin"],
    weight: "400"
});

const geistMono = Noto_Sans_Mono({
    subsets: ["latin"],
    weight: "400"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistMono.className} ${lilita.className}`}>
        {children}
        </body>
        </html>
    );
}
